services:
  database:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    ports:
      - "5454:5432"
    environment:
      POSTGRES_USER: english-master
      POSTGRES_PASSWORD: english-master

  adminer:
    image: adminer
    restart: always
    ports:
      - "8083:8080"
